# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datafast < Formula
  desc "CLI for the DataFast analytics API"
  homepage "https://github.com/dqhieu/datafast-cli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_darwin_amd64.tar.gz"
      sha256 "d383ccbd9fb041f296b114ea9b75a5edcb19acab9072a62a51e3f69069360fb1"

      define_method(:install) do
        bin.install "datafast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_darwin_arm64.tar.gz"
      sha256 "c91bf408e57a4616e9d1bf5c766bef885106db5213469e52aee34fdcc48cd574"

      define_method(:install) do
        bin.install "datafast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_linux_amd64.tar.gz"
      sha256 "6ef5593657dfcfedf43415d768ae94452d48fb1234a9d4364b21c5fc5e820f92"
      define_method(:install) do
        bin.install "datafast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_linux_arm64.tar.gz"
      sha256 "61e93ab8a223716e3e477444ac01fcc048471bce8bcc3dcd8158477d02e3247a"
      define_method(:install) do
        bin.install "datafast"
      end
    end
  end
end
