# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datafast < Formula
  desc "CLI for the DataFast analytics API"
  homepage "https://github.com/dqhieu/datafast-cli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_darwin_amd64.tar.gz"
      sha256 "785ea56dca8a14e468e98402f7c2afc0af85b7f732b060bcac2312531ee990c4"

      define_method(:install) do
        bin.install "datafast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_darwin_arm64.tar.gz"
      sha256 "14e7847994b4bc5f7890997fd13c04171bdc7671d8f3c31dd36f88cb688980ca"

      define_method(:install) do
        bin.install "datafast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_linux_amd64.tar.gz"
      sha256 "77e29d9a3f7a9822fe284301995df0bb017b19d0cafeef93358554d6a822cec0"
      define_method(:install) do
        bin.install "datafast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dqhieu/datafast-cli/releases/download/v1.0.0/datafast_linux_arm64.tar.gz"
      sha256 "2181753121de3f60bea7afa913a25587b3ffd4683ece5f442fd35645edf70198"
      define_method(:install) do
        bin.install "datafast"
      end
    end
  end
end
